---
- hosts: all
  become: true
  vars_files:
    - /root/secrets.yml  # Original secrets file

  tasks:
    - name: Update apt packages
      apt:
        force_apt_get: true
        upgrade: yes  # Perform a regular upgrade
        update_cache: true
      register: update_result  # Register the result of the update task

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify if reboot is required
      debug:
        msg: "Reboot is required"
      when: reboot_required.stat.exists

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: true

    - name: Notify that the update process is finished
      debug:
        msg: "Update process completed successfully."

    - name: Check if the update was successful
      debug:
        msg: "Update was successful."
      when: update_result.changed  # Check if any changes were made during the update

    - name: Debug before sending Telegram success message
      debug:
        msg: "Attempting to send success message to Telegram"
      when: update_result.changed

    - name: Send success message to Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage"
        method: POST
        body: 
          chat_id: "{{ chat_id }}"
          text: "Update process completed successfully on {{ inventory_hostname }}."
        headers:
          Content-Type: "application/json"
        return_content: yes  # Capture the response
      register: telegram_response_success
      when: update_result.changed
      check_mode: no  # Prevent skipping in check mode

    - name: Debug Telegram success response
      debug:
        var: telegram_response_success
      when: update_result.changed

    - name: Send failure message to Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage"
        method: POST
        body: 
          chat_id: "{{ chat_id }}"
          text: "No updates were made on {{ inventory_hostname }}."
        headers:
          Content-Type: "application/json"
        return_content: yes  # Capture the response
      register: telegram_response_failure
      when: not update_result.changed
      check_mode: no  # Prevent skipping in check mode

    - name: Debug Telegram failure response
      debug:
        var: telegram_response_failure
      when: not update_result.changed