---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      apt:
        force_apt_get: true
        upgrade: dist
        update_cache: true
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - debug:
        msg: "Reboot is required"
      when: reboot_required.stat.exists
      
    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: true